// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ddVW3IoMNwakJ32A8qsmdR5JUb_yXPs',
    appId: '1:820959083332:web:635a2a41096a27554cb511',
    messagingSenderId: '820959083332',
    projectId: 'employee-manager-452b0',
    authDomain: 'employee-manager-452b0.firebaseapp.com',
    storageBucket: 'employee-manager-452b0.firebasestorage.app',
    measurementId: 'G-PNGCF792XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgDzMUFluYRoypA9Vngic70y7cBDTw1V4',
    appId: '1:820959083332:android:cbac070140778ae84cb511',
    messagingSenderId: '820959083332',
    projectId: 'employee-manager-452b0',
    storageBucket: 'employee-manager-452b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWiOj6WzR3n24YNzCbdJCIkSHJHvzr3I',
    appId: '1:820959083332:ios:0435d0babc14c3474cb511',
    messagingSenderId: '820959083332',
    projectId: 'employee-manager-452b0',
    storageBucket: 'employee-manager-452b0.firebasestorage.app',
    iosBundleId: 'com.example.employeeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWiOj6WzR3n24YNzCbdJCIkSHJHvzr3I',
    appId: '1:820959083332:ios:0435d0babc14c3474cb511',
    messagingSenderId: '820959083332',
    projectId: 'employee-manager-452b0',
    storageBucket: 'employee-manager-452b0.firebasestorage.app',
    iosBundleId: 'com.example.employeeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2ddVW3IoMNwakJ32A8qsmdR5JUb_yXPs',
    appId: '1:820959083332:web:252c721b2d7c5d5b4cb511',
    messagingSenderId: '820959083332',
    projectId: 'employee-manager-452b0',
    authDomain: 'employee-manager-452b0.firebaseapp.com',
    storageBucket: 'employee-manager-452b0.firebasestorage.app',
    measurementId: 'G-3KKMMSMJR0',
  );
}
